version: '3.5'

services:
  ls:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      MEMORY: "2G"
      ONLINE_MODE: "FALSE"
      OPS: "ItsJotaroKujo"
    volumes:
      - ./data/ls:/data
    restart: always
  smp:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MEMORY: "10G"
      ONLINE_MODE: "FALSE"
      OPS: "ItsJotaroKujo"
    ports:
      - 25555:8123
      - 24454:24454/udp
    volumes:
      - ./data/fabricsmp:/data
    restart: always
  bungeecord:
    image: itzg/bungeecord
    environment:
      BUNGEE_JAR_REVISION: "1"
      ENABLE_RCON: "TRUE"
    ports:
      - 25565:25577
    volumes:
      - ./data/bc:/server
      - ./config.yml:/config/config.yml
    restart: always
